apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: your_dockerhub/python-app:latest
        volumeMounts:
        - name: user-db
          mountPath: /app/data
        env:
        - name: DB_PATH
          value: /app/data/users.db
      volumes:
      - name: user-db
        emptyDir: {}  # Or use PersistentVolumeClaim for real persistence
